-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.25-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table mangos.npc_trainer_greeting
CREATE TABLE IF NOT EXISTS `npc_trainer_greeting` (
  `entry` int(11) unsigned NOT NULL DEFAULT 0,
  `content_default` text NOT NULL,
  `content_loc1` text NOT NULL,
  `content_loc2` text NOT NULL,
  `content_loc3` text NOT NULL,
  `content_loc4` text NOT NULL,
  `content_loc5` text NOT NULL,
  `content_loc6` text NOT NULL,
  `content_loc7` text NOT NULL,
  `content_loc8` text NOT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Dumping data for table mangos.npc_trainer_greeting: 489 rows
/*!40000 ALTER TABLE `npc_trainer_greeting` DISABLE KEYS */;
REPLACE INTO `npc_trainer_greeting` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
	(198, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(328, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(331, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(375, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(376, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(377, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(459, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(460, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(461, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(514, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(543, '', '', '', '', '', '', '', '', ''),
	(812, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(837, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(895, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(906, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(908, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(911, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(912, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(913, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(914, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(915, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(916, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(917, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(918, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(925, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(926, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(927, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(928, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(944, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(985, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(986, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(987, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(988, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(1103, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(1215, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(1218, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(1226, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(1228, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(1229, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(1231, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(1232, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(1234, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(1241, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(1292, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(1300, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(1317, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(1346, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(1355, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(1382, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(1385, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(1386, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(1404, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(1411, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(1430, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(1458, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(1470, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(1473, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(1632, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(1651, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(1676, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(1680, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(1681, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(1683, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(1699, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(1700, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(1701, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(1702, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(1703, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(1901, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(2114, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(2119, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(2122, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(2123, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(2124, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(2126, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(2127, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(2128, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(2129, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(2130, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(2131, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(2132, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(2326, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(2327, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(2329, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(2367, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(2390, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(2391, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(2399, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(2485, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(2489, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(2492, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(2627, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(2704, '', '', '', '', '', '', '', '', ''),
	(2798, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(2818, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(2834, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(2836, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(2837, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(2855, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(2856, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(2878, '', '', '', '', '', '', '', '', ''),
	(2879, '', '', '', '', '', '', '', '', ''),
	(2998, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3001, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(3004, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(3007, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3009, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(3011, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(3013, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(3026, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(3028, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(3030, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3031, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3032, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3033, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3034, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3036, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3038, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3039, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3040, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3041, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3042, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3043, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3044, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3045, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3046, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3047, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(3048, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(3049, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(3059, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3060, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3061, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3062, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3063, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3064, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3065, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3066, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3067, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(3069, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3087, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(3136, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3137, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(3153, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3154, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3155, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3156, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(3157, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3169, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3170, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3171, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3172, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(3173, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3174, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3175, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(3179, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(3181, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(3184, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(3185, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(3290, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(3306, '', '', '', '', '', '', '', '', ''),
	(3324, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(3325, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(3326, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(3327, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3328, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3332, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(3344, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3345, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(3347, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(3352, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3353, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3354, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3355, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3357, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(3363, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(3365, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3373, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(3399, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(3401, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3403, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(3404, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(3406, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3407, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3408, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3478, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3484, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(3494, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(3523, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(3545, '', '', '', '', '', '', '', '', ''),
	(3549, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3555, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(3557, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(3593, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3594, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3595, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3596, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3597, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3598, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(3599, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(3600, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3601, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3602, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(3603, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(3604, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(3605, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3606, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(3607, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(3620, '', '', '', '', '', '', '', '', ''),
	(3622, '', '', '', '', '', '', '', '', ''),
	(3624, '', '', '', '', '', '', '', '', ''),
	(3688, '', '', '', '', '', '', '', '', ''),
	(3690, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(3698, '', '', '', '', '', '', '', '', ''),
	(3703, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3704, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(3706, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3707, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(3963, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(3964, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(3965, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(3967, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(4087, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(4089, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(4090, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4091, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4092, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4138, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(4146, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(4156, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(4159, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(4160, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(4163, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4165, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(4193, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(4204, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(4205, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(4210, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(4211, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(4212, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(4213, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(4214, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4215, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4217, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(4218, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(4219, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(4254, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(4258, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(4320, '', '', '', '', '', '', '', '', ''),
	(4552, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(4563, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(4564, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(4565, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(4566, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(4567, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(4568, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(4573, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(4576, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(4578, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(4582, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4583, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4584, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(4588, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(4591, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(4593, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(4594, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(4595, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(4596, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(4598, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(4606, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4607, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4608, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(4611, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(4614, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(4616, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(4732, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(4752, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(4753, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(4772, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(4773, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(4898, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(4900, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(5032, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(5037, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(5038, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(5040, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(5041, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(5113, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(5114, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(5115, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5116, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5117, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5127, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(5137, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(5141, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(5142, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(5143, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(5144, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5145, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5146, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5147, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(5148, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(5149, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(5150, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(5153, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(5157, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(5159, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(5161, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(5164, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(5165, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(5166, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(5167, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(5171, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5172, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5173, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5174, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(5177, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(5392, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(5479, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(5480, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(5482, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(5484, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(5489, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(5491, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(5492, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(5493, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(5495, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5496, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5497, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5498, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5499, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(5501, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5502, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(5504, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(5505, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(5506, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(5511, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(5513, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(5515, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5516, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5517, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(5518, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(5564, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(5566, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(5612, 'Hello, warlock! Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(5690, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(5695, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(5759, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(5784, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(5880, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5882, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5883, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5884, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5885, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(5938, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(5939, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(5941, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(5943, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(5957, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(5958, 'Welcome!', '', '', '', '', '', '', '', 'Добро пожаловать!'),
	(5994, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(6014, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(6018, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(6094, 'Here, let me show you how to bind those wounds....', '', '', '', '', '', '', '', 'Подойди, я покажу тебе, как перевязывать раны.'),
	(6251, 'Hello, warlock!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gчернокнижник:чернокнижница;! Ты будешь учиться?'),
	(6286, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(6287, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6288, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6289, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6290, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6291, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6292, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6295, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6297, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(6299, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(6306, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6387, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(6707, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(7087, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(7088, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(7089, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(7230, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(7231, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(7232, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(7311, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(7312, 'Hello, mage!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, маг! Ты $gготов:готова; учиться?'),
	(7315, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(7406, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(7866, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7867, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7868, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7869, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7870, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7871, 'Greetings! Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(7944, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(7946, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(7948, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(7949, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(7953, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(7954, 'Hello!  Can I teach you something?', '', '', '', '', '', '', '', 'Здравствуйте! Могу ли я вас чему-то обучить?'),
	(8126, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(8128, 'You have not lived until you have dug deep into the earth.', '', '', '', '', '', '', '', 'Кто никогда не рылся в земле, тот, считай, и не жил!'),
	(8140, 'Hello, paladin!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, паладин! Ты $gпришел:пришла; за знаниями?'),
	(8141, 'Hello, warrior!  Ready for some training?', '', '', '', '', '', '', '', 'Привет тебе, воин! Ты хочешь учиться?'),
	(8142, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(8144, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(8146, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(8153, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(8306, 'Can I teach you how to turn the meat you find on beasts into a feast?', '', '', '', '', '', '', '', 'Хочешь, научу, как устроить из добычи настоящее пиршество?'),
	(8308, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(8736, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(8738, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(9465, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(9584, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(10086, '', '', '', '', '', '', '', '', ''),
	(10088, '', '', '', '', '', '', '', '', ''),
	(10089, '', '', '', '', '', '', '', '', ''),
	(10090, '', '', '', '', '', '', '', '', ''),
	(10930, 'Hello, hunter!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gохотник:охотница;! Ну что, будешь учиться?'),
	(10993, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11017, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11025, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11031, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11037, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11048, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11050, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11051, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11052, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11072, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11073, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11074, 'Enchanting is the art of improving existing items through magic. ', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11097, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11098, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11146, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(11177, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(11178, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(11397, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(11401, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(11406, 'Hello, priest!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gжрец:жрица;! Стремишься к новым знаниям?'),
	(11557, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11865, '', '', '', '', '', '', '', '', ''),
	(11866, '', '', '', '', '', '', '', '', ''),
	(11867, '', '', '', '', '', '', '', '', ''),
	(11868, '', '', '', '', '', '', '', '', ''),
	(11869, '', '', '', '', '', '', '', '', ''),
	(11870, '', '', '', '', '', '', '', '', ''),
	(12025, 'Searching for herbs requires both knowledge and instinct.', '', '', '', '', '', '', '', 'Чтобы разбираться в травах, нужны и знания, и чутье.'),
	(12030, 'It requires a steady hand to remove the leather from a slain beast.', '', '', '', '', '', '', '', 'Чтобы снять шкуру с убитого зверя, нужна твердая рука.'),
	(12032, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(12042, 'Hello, druid!  Ready for some training?', '', '', '', '', '', '', '', 'Приветствую тебя, друид! Тебе нужны новые знания?'),
	(12961, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(13084, '', '', '', '', '', '', '', '', ''),
	(13283, 'Hello, rogue!  Ready for some training?', '', '', '', '', '', '', '', 'Привет, $gразбойник:разбойница;! Ну что, будешь учиться?'),
	(13417, 'Hello, shaman!  Ready for some training?', '', '', '', '', '', '', '', 'Здравствуй, $gшаман:шаманка;! Хочешь поучиться?'),
	(14740, 'I can teach you how to use a fishing pole to catch fish.', '', '', '', '', '', '', '', 'Я могу научить тебя ловить рыбу.'),
	(1246, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(5500, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(11041, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(11042, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(11044, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(11046, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(11047, 'With alchemy you can turn found herbs into healing and other types of potions.', '', '', '', '', '', '', '', 'Освоив алхимию, ты сможешь варить зелья из найденных растений.'),
	(957, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(1383, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(4605, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(10266, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(10276, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(10277, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(10278, 'Care to learn how to turn the ore that you find into weapons and metal armor?', '', '', '', '', '', '', '', 'Хочешь, я научу тебя, как из найденной руды делать оружие и доспехи?'),
	(2857, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(3412, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(4586, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11026, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11028, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(11029, 'Engineering is very simple once you grasp the basics.', '', '', '', '', '', '', '', 'В инженерном деле главное - понять основы. Остальное само придет.'),
	(223, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(1466, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(3008, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(5811, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11081, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11083, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11084, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11096, 'Greetings!  Can I teach you how to turn beast hides into armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь научиться делать доспехи из шкур животных?'),
	(11049, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?', '', '', '', '', '', '', '', 'Здравствуй! Хочешь, я научу тебя шить доспехи из ткани?'),
	(11065, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11066, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11067, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11068, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11070, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.'),
	(11071, 'Enchanting is the art of improving existing items through magic.', '', '', '', '', '', '', '', 'Наложение чар - это искусство улучшения материальных объектов с помощью магии.');
/*!40000 ALTER TABLE `npc_trainer_greeting` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
